version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    exclude-paths:
      - "modules/deployment-helper-regional/src/terraform-stacks"
    schedule:
      interval: "weekly"
