name: Lint and validate Terraform

on:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/lint-and-validate-terraform.yml"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  terraform_validation:
    name: Terraform Lint and Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.4.2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.9.0
      - name: terraform fmt -check=true -recursive
        run: terraform fmt -check=true -recursive
      - name: terraform init -backend=false
        run: terraform init -backend=false
      - name: terraform validate
        run: terraform validate

  call_tflint_workflow:
    name: Run TFLint
    needs: terraform_validation
    uses: ./.github/workflows/tflint.yml
