name: Lint and validate Terraform

on:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/lint-and-validate-terraform.yml"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  terraform_validation:
    name: Terraform Lint and Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.9.0
      - run: terraform fmt -check=true -recursive
      - run: terraform init -backend=false
      - run: terraform validate

  call_tflint_workflow:
    name: Run TFLint
    needs: terraform_validation
    uses: ./.github/workflows/tflint.yml
