name: Lint and validate Terraform

on:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/lint-and-validate-terraform.yml"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  terraform_validation:
    name: Terraform Lint and Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4.4.2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0
      - name: terraform fmt -check=true -recursive
        run: terraform fmt -check=true -recursive
      - name: terraform init -backend=false
        run: terraform init -backend=false
      - name: terraform validate
        run: terraform validate

  call_tflint_workflow:
    name: Run TFLint
    needs: terraform_validation
    uses: ./.github/workflows/tflint.yml
