name: TFLint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          tflint_version: v0.58.1
          checksums: |
            2fea1af8e8602d4d9e4253a588ac66f17bf36152cafb51f4d929b8bc6335e740
      - name: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: tflint --init
      - name: tflint
        run: tflint
