name: TFLint

on:
  workflow_call:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup TFLint with checksum verification
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6
        with:
          tflint_version: v0.58.0
          checksums: |
            1e8ccdf3e4b57ba154545b4343621bf46f25ca8f5cc97e36432469752f7ef0c0 

      - name: Initialise & Install TFLint AWS Ruleset Plugin
        run: tflint --init

      - name: Run TFLint
        run: tflint
