name: TFLint

on: [push, pull_request]

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TFLint with checksum verification
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.58.0

      - name: Install TFLint AWS Ruleset Plugin
        run: tflint --init
        run: tflint --install-plugin=tflint-ruleset-aws

      - name: Run TFLint
        run: tflint