name: TFLint

on:
  workflow_call:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TFLint with checksum verification
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.58.0
          checksum:  terraform-linters/setup-tflint@65effd5f53a9247b550ede916c626b4ba20935c5

      - name: Initialise & Install TFLint AWS Ruleset Plugin
        run: tflint --init

      - name: Run TFLint
        run: tflint